### ISSUE TITLE
Let's Talk: EMP

### ISSUE THREAD

**Issue by LemmaEOF** [CottonMC/cotton-energy#11]
The EMP system is something we haven't discussed much yet. It's an IC2-style voltage shutdown, but we don't have much of a standard for what it should *do*, and a few folks think we shouldn't have it. Our options:

- Keep it as-is. There's no requirement for it to do *anything* currently, so mods can just ignore it or have config disable it. It's a void, so it can just be empty.
- Establish a standard for what an EMP should do. This could be divisive, as enforcing a code of conduct on a power API would make people less likely/willing to use it.
- Remove it entirely. I'm personally against this option, since it would limit a few creative uses for it. EMPs could be used for a lot of different systems, both in magic and tech, so I think it's better to keep around then remove.

**Comment by LemmaEOF** [comment]
@falkreon panno suggests making emp default to `{}` so folks don't have to define it themselves. What's your take on that?

**Comment by falkreon** [comment]
EMP should have clear guidelines: Machines SHOULD remove that much power from the storage so that the machine goes dark. (as in rfc 2119 SHOULD, "there may exist valid reasons in particular circumstances to ignore a particular item, but the full implications must be understood and  carefully weighed before choosing a different course")

So default implementations should do that and people are welcome to make it do `{}`.

Also, I'm lookiung at the energy, UM, and general/development channels. I'd like to see the complaints so I can consider or address them.

**Comment by LemmaEOF** [comment]
Here's a basic default:
```java
default void emp(int strength) {
		int toExtract = extractEnergy(strength, ActionType.SIMULATE);
		if (toExtract > 0) extractEnergy(toExtract, ActionType.PERFORM);
	}```

**Comment by falkreon** [comment]
no need to simulate if nothing changes on a failure

**Comment by falkreon** [comment]
Alright, looks like we've nailed this down as much as we're going to for now.
