### ISSUE TITLE
Let's talk about units!

### ISSUE THREAD

**Issue by falkreon** [CottonMC/cotton-energy#5]
The Tesla repo had a [wonderfully productive, serious, and definitely-not-silly discussion](https://github.com/Darkhax-Minecraft/Tesla/issues/4) about naming, and I think it's about that time for us too. Speaking about our energy without a unit is starting to become bothersome. Does anyone have a suggestion for the energy unit name, and its abbreviation?

**Comment by Pannoniae** [comment]
Either we re-use something (and kindly ask the original authors about it), or invent something new.
In the later case, I'd vote for "real" units (V, A, W)

**Comment by LemmaEOF** [comment]
The issue with volts, amps, and watts is that none of them really represent a system that can have definite integers for “this is exactly how much energy this is holding”. The closest you can get in common use is milliamp-hours, or mAh, which you’ll find on battery packs and such, but even that is dependent on time. I honestly think comparisons to real-life electricity are a bad idea, since real-life electricity is confusing as hell and we don't need to stick to them.

On top of that, naming our system after another previous system would cause a lot of confusion about how our system works, so I think we should think up a new name.

**Comment by falkreon** [comment]
Well okay, but current is a small part of the wider concept of "Work", or "Potential". There are a lot of decent real-world work units like Joules, which gave rise to the original MJ. Newton-Meter is the same unit, Foot-Pound is the imperial version, KW/h and horsepower-hour are similar to your mAh, litre-atmospheres are handy for hydraulics, and Calories relate pretty nicely to the origin in furnace burn time. I use enthalpy (H) elsewhere.

Whatever it winds up as, a comparison to "EU" would be valid and useful because of our similar voltage tiering and packetization. Maybe "WU" for Work Units?

**Comment by LemmaEOF** [comment]
that might be good! Then it could be used for systems other than explicitly electricity too. Stuff like heat or mechanical motion or the like.

**Comment by LemmaEOF** [comment]
With the potential move to types, would we have it written as `<number> WU - <primary type>` or a multiline thing with `<number> WU` at the top and `accepts <list of types>` below?

**Comment by falkreon** [comment]
I don't understand flavors at all tbh

**Comment by falkreon** [comment]
This is still open for discussion, but I suspect the next PR will address the discussion in a more focused way.
